title: Mark Lee (이원하)
description: My Personal Blog
author: Mark Lee (이원하)
logo: /hcz-jekyll-blog/static/img/avatar.png
about: Developer(?)

baseurl: "https://ericnjennifer.github.io"
url: ""

allowsearch: true

disqus-shortname: ericnjennifer
google_analytics: UA-69111439-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
